// Generated by CoffeeScript 1.3.1
var net, server, testCase;

net = require('net');

server = require('..').server;

testCase = require('nodeunit').testCase;

module.exports = testCase({
  setUp: function(next) {
    this.connection = net.createConnection(25);
    return next();
  },
  testHello: function(test) {
    test.ok(true);
    return test.done();
  },
  tearDown: function(next) {
    this.connection.end();
    return next();
  }
});
