// Generated by CoffeeScript 1.3.1
var http;

http = require('http');

exports.API = (function() {

  API.name = 'API';

  function API(host, port, next) {
    var _this = this;
    this.server = http.createServer(function(req, res) {
      return _this.handle(req, res);
    });
    this.server.listen(port, host, function() {
      if (next != null) {
        return next();
      }
    });
  }

  API.prototype.handle = function(req, res) {
    res.writeHead(200);
    return res.end('Hello World!');
  };

  return API;

})();
