// Generated by CoffeeScript 1.3.1
var http;

http = require('http');

exports.API = (function() {

  API.name = 'API';

  function API(host, port, next, store) {
    var _this = this;
    this.store = store;
    this.server = http.createServer(function(req, res) {
      return _this.handle(req, res);
    });
    this.server.listen(port, host, function() {
      if (next != null) {
        return next();
      }
    });
  }

  API.prototype.handle = function(req, res) {
    if (req.url === '/emails') {
      res.writeHead(200, {
        'Content-Type': 'application/json'
      });
      return res.end(JSON.stringify(this.store.all()));
    } else if (req.url === '/ping') {
      res.writeHead(200, {
        'Content-Type': 'text/html'
      });
      return res.end('<a href="https://github.com/jamierumbelow/postmaster">Postmaster</a> reporting for duty');
    } else {
      res.writeHead(404, {
        'Content-Type': 'text/html'
      });
      return res.end('<h1>404 Not Found</h1>');
    }
  };

  return API;

})();
