// Generated by CoffeeScript 1.3.1

exports.Parser = (function() {
  var COMMANDS;

  Parser.name = 'Parser';

  function Parser() {}

  COMMANDS = ['HELO', 'EHLO', 'MAIL FROM', 'RCPT TO'];

  Parser.prototype.parse = function(string) {
    var ret;
    ret = '';
    COMMANDS.forEach(function(command) {
      var pattern;
      pattern = new RegExp("^" + command, 'm');
      if (pattern.test(string)) {
        return ret = command;
      }
    });
    return {
      command: ret
    };
  };

  return Parser;

})();
