// Generated by CoffeeScript 1.3.1
var net;

net = require('net');

exports.Server = (function() {

  Server.name = 'Server';

  function Server(host, port) {
    var _this = this;
    this.host = host != null ? host : 'localhost';
    this.port = port != null ? port : 5666;
    this.createServer().listen(this.port, this.host, function() {
      return console.log("Postmaster reporting for duty on " + _this.host + ":" + _this.port);
    });
  }

  Server.prototype.handler = function(socket) {
    return socket.write('Welcome to Postmaster\n');
  };

  Server.prototype.createServer = function() {
    return net.createServer(this.handler);
  };

  return Server;

})();
