// Generated by CoffeeScript 1.3.1
var net, version;

net = require('net');

version = require('../package.json').version;

exports.Server = (function() {

  Server.name = 'Server';

  function Server(next, host, port) {
    var _this = this;
    this.host = host != null ? host : 'localhost';
    this.port = port != null ? port : 5666;
    this.server = this.createServer();
    this.server.listen(this.port, this.host, function() {
      console.log("Postmaster reporting for duty on " + _this.host + ":" + _this.port);
      if (next != null) {
        return next();
      }
    });
    this.server.on('connection', function(socket) {
      var buffer;
      socket.setEncoding('utf8');
      socket.on('connect', function() {
        return socket.write("220 " + _this.host + " Postmaster " + version + "\r\n");
      });
      buffer = '';
      return socket.on('data', function(data) {
        var lines;
        lines = (buffer + data).split("\r\n");
        buffer = lines.pop();
        return lines.forEach(function(line, index) {
          return _this.handler(socket, line);
        });
      });
    });
  }

  Server.prototype.handler = function(socket, data) {
    var name;
    if (data.slice(0, 4) === "HELO") {
      name = data.match(/^HELO (.*)$/m)[1];
      return socket.write("250 Hello " + name + ", nice to meet you\r\n");
    }
  };

  Server.prototype.createServer = function() {
    return net.createServer();
  };

  Server.prototype.close = function() {
    return this.server.close();
  };

  return Server;

})();
