// Generated by CoffeeScript 1.3.1

Object.prototype.length = function() {
  var key, size;
  size = 0;
  for (key in this) {
    if (this.hasOwnProperty(key)) {
      size++;
    }
  }
  return size;
};

exports.Store = (function() {

  Store.name = 'Store';

  function Store() {
    this.emails = {};
    this.ids = [];
  }

  Store.prototype.add = function(email) {
    var new_id;
    new_id = this.ids.length > 0 ? this.ids.slice(-1)[0] + 1 : 1;
    this.emails[new_id] = email;
    this.ids.push(new_id);
    return new_id;
  };

  Store.prototype.remove = function(id) {
    delete this.emails[id];
    return this.ids.splice(this.ids.indexOf(id), 1);
  };

  Store.prototype.all = function() {
    return this.emails;
  };

  return Store;

})();
